import { renderSolarField, solarAltitude } from '../astronomy/solar-field.js';
import { getSpaEvents, getSpaPosition } from '../astronomy/solar-spa.js';

(() => {
  const VIEWBOX = { width: 3025.3333, height: 2137.3333 };
  const UTC_OFFSET = 8 * 60 * 60 * 1000;
  const app = document.querySelector('.app-shell');
  const mapImage = document.querySelector('.map-image');
  const terrain = document.querySelector('#terrainVisualLayer');
  const solar = document.querySelector('#solarFieldLayer');
  const cityLayer = document.querySelector('#cityLayer');
  const analysis = document.querySelector('#analysisPanel');
  const compare = document.querySelector('#comparePanel');
  const astronomy = document.querySelector('#astronomyPanel');
  const hint = document.querySelector('#selectionHint');
  const fallback = [
    ['哈尔滨','interior',2293.3535,478.5389,126.535,45.8028],['乌鲁木齐','interior',789.5632,547.7053,87.6168,43.8256],['拉萨','interior',771.3615,1376.7095,91.1408,29.6456],['北京','capital',1958.1115,860.7744,116.4047,39.9042],['西安','interior',1630.4811,1202.9661,108.9398,34.3416],['成都','interior',1404.7802,1397.5587,104.0665,30.5723],['武汉','interior',1870.7434,1397.5587,114.3055,30.5928],['上海','coast',2231.1368,1342.9536,121.4737,31.2304],['广州','coast',1856.1821,1823.4782,113.2644,23.1291],['台北','island',2271.1805,1683.4906,121.5654,25.033],['海口','island',1699.6476,2011.121,110.1999,20.0442],['漠河','border',2121.9267,110.8648,122.5376,52.97],['抚远','border',2580.6092,289.2414,134.2957,48.367],['喀什','border',243.5125,656.9155,75.9897,39.4704],['曾母暗沙','island',2755.3454,2043.2222,112.2963,3.8329]
  ].map(([name,role,x,y,longitude,latitude]) => ({name,role,x,y,longitude,latitude}));
  const state = { points: [], selected: [], minute: 300, season: 'summer-solstice', date: '2026-06-21', mode: 'dawn-progress', playing: false, timer: null };
  const $ = (s) => document.querySelector(s);

  const adapt = (p) => { const v = Array.isArray(p.pickedV) ? p.pickedV : [p.x,p.y]; const x=Number(v?.[0]), y=Number(v?.[1]), longitude=Number(p.longitudeDeg ?? p.longitude), latitude=Number(p.latitudeDeg ?? p.latitude); return p.name && [x,y,longitude,latitude].every(Number.isFinite) ? {...p,x,y,longitude,latitude,displayRole:p.role==='border'?'extreme-point':p.role} : null; };
  const bjtUtc = (minutes) => { const [y,m,d]=state.date.split('-').map(Number); return new Date(Date.UTC(y,m-1,d,0,minutes)-UTC_OFFSET); };
  const bjt = (date) => new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(date);
  const solarEvent = (p,target) => { const events=getSpaEvents(state.date,p); const event=target===-.833?events.sunrise:target===-6?events.civilDawn:target===-12?events.nauticalDawn:events.astronomicalDawn; return event ? (event.getTime()-bjtUtc(0).getTime())/60000 : null; };
  const seasonDates = { 'spring-equinox': ['春分','2026-03-20'], 'summer-solstice': ['夏至','2026-06-21'], 'autumn-equinox': ['秋分','2026-09-23'], 'winter-solstice': ['冬至','2026-12-22'] };
  const clampPercent = (minutes) => Math.max(0, Math.min(100, ((minutes - 180) / 420) * 100));
  const clockText = (minutes) => { const d=bjtUtc(minutes); return bjt(d); };

  function syncMarkers() { const lr=cityLayer.getBoundingClientRect(), ir=mapImage.getBoundingClientRect(); if(!lr.width||!ir.width)return; const sr=VIEWBOX.width/VIEWBOX.height, br=ir.width/ir.height, scale=br>sr?ir.height/VIEWBOX.height:ir.width/VIEWBOX.width, ox=(ir.width-VIEWBOX.width*scale)/2, oy=(ir.height-VIEWBOX.height*scale)/2; cityLayer.querySelectorAll('.city-marker').forEach((m)=>{const p=m._point;m.style.left=`${ir.left-lr.left+ox+p.x*scale}px`;m.style.top=`${ir.top-lr.top+oy+p.y*scale}px`;m.classList.toggle('selected',state.selected.includes(m.dataset.name));}); }
  function placeMarkers(points) { cityLayer.replaceChildren(); points.filter(p=>!['三沙','曾母暗沙','黄岩岛'].includes(p.name)).forEach((p)=>{const m=document.createElement('button');m.type='button';m.className='city-marker';m.dataset.name=p.name;m.dataset.role=p.displayRole||p.role;m.setAttribute('aria-label',`选择${p.name}`);m.innerHTML='<span class="city-marker-pin" aria-hidden="true"></span><span class="city-marker-label"></span>';m.querySelector('.city-marker-label').textContent=p.name;m._point=p;m.addEventListener('click',()=>selectCity(p.name));cityLayer.append(m);});syncMarkers();}
  function selectCity(name) { if(!state.points.some(p=>p.name===name))return; if(state.selected.length===2)state.selected=[name]; else if(!state.selected.includes(name))state.selected.push(name); hint.textContent=state.selected.length===2?`${state.selected[0]} 与 ${state.selected[1]} 对比中`:`${name} 已选中，再选择一座城市进行对比`; if(state.selected.length===2)setMode('location-compare'); updatePanel();syncMarkers(); }
  function updatePanel() { const a=state.points.find(p=>p.name===state.selected[0])||state.points.find(p=>p.name==='北京')||fallback[3], b=state.points.find(p=>p.name===state.selected[1])||state.points.find(p=>p.name==='乌鲁木齐')||fallback[1]; ['rulerCityOne','compareNameOne'].forEach(id=>{const n=$(`#${id}`);if(n)n.textContent=a.name;}); ['rulerCityTwo','compareNameTwo'].forEach(id=>{const n=$(`#${id}`);if(n)n.textContent=b.name;}); const ea=solarEvent(a,-.833), eb=solarEvent(b,-.833), ca=solarEvent(a,-6), cb=solarEvent(b,-6); const one=$('#sunriseOne'),two=$('#sunriseTwo'),diff=$('#sunriseDifference'); if(one)one.textContent=ea==null?'--:--':bjt(bjtUtc(ea));if(two)two.textContent=eb==null?'--:--':bjt(bjtUtc(eb));if(diff&&ea!=null&&eb!=null){const mins=Math.round(Math.abs(eb-ea));diff.textContent=`${Math.floor(mins/60)}小时${String(mins%60).padStart(2,'0')}分`;} [['altitudeOne',a],['altitudeTwo',b]].forEach(([id,p])=>{const n=$(`#${id}`);if(n){const position=getSpaPosition(bjtUtc(state.minute),p);n.textContent=position?`${position.altitudeDeg.toFixed(1)}°`:'--.-°';}}); ['longitudeOne','longitudeTwo'].forEach((id,i)=>{const n=$(`#${id}`);if(n)n.textContent=`${[a,b][i].longitude.toFixed(1)}°E`;}); [['localTimeOne',a],['localTimeTwo',b]].forEach(([id,p])=>{const n=$(`#${id}`);if(n)n.textContent=bjt(bjtUtc(state.minute-(p.longitude-120)*4));}); [['civilDawnOne',ca],['civilDawnTwo',cb]].forEach(([id,m])=>{const n=$(`#${id}`);if(n)n.textContent=m==null?'--:--':bjt(bjtUtc(m));}); const scale=document.querySelectorAll('.track-scale span'); if(scale[0])scale[0].textContent=`${a.name} 日出 ${ea==null?'--:--':bjt(bjtUtc(ea))}`; if(scale[1])scale[1].textContent=`${b.name} 日出 ${eb==null?'--:--':bjt(bjtUtc(eb))}`; const narrative=$('#rulerNarrative');if(narrative)narrative.textContent=`${a.name} 与 ${b.name} 的日出节律对比，当前为 NREL SPA 计算。`; }
  function syncDerivedUi() {
    const a=state.points.find(p=>p.name===state.selected[0])||state.points.find(p=>p.name==='北京')||fallback[3];
    const b=state.points.find(p=>p.name===state.selected[1])||state.points.find(p=>p.name==='乌鲁木齐')||fallback[1];
    const ea=solarEvent(a,-.833), eb=solarEvent(b,-.833);
    const set=(id,value)=>{const n=$(`#${id}`);if(n)n.textContent=value;};
    set('rulerSunriseOne',ea==null?'--:--':bjt(bjtUtc(ea))); set('rulerSunriseTwo',eb==null?'--:--':bjt(bjtUtc(eb)));
    const delta=ea!=null&&eb!=null?Math.round(Math.abs(eb-ea)):null; set('rulerDifference',delta==null?'--':`${Math.floor(delta/60)}小时${String(delta%60).padStart(2,'0')}分`); set('summaryDifference',delta==null?'--':`${Math.floor(delta/60)}小时${String(delta%60).padStart(2,'0')}分`); set('summaryEarliest',ea!=null&&eb!=null?(ea<=eb?a.name:b.name):'--');
    set('timelineCityOne',`${a.name}日出 ${ea==null?'--:--':bjt(bjtUtc(ea))}`); set('timelineCityTwo',`${b.name}日出 ${eb==null?'--:--':bjt(bjtUtc(eb))}`);
    const mark=(id,m)=>{const n=$(`#${id}`);if(n)n.style.left=`${clampPercent(m??0)}%`;}; mark('markOne',ea); mark('markTwo',eb); const ratio=clampPercent(state.minute); const handle=$('#trackHandle'),progress=$('#trackProgress'); if(handle)handle.style.left=`${ratio}%`; if(progress)progress.style.right=`${100-ratio}%`;
    const coverage=state.points.filter(p=>p.role!=='border'&&solarAltitude(bjtUtc(state.minute),p.longitude,p.latitude)>=-6).length; set('summaryCoverage',`${(coverage/Math.max(1,state.points.filter(p=>p.role!=='border').length)*100).toFixed(1)}%`);
    set('stageAstronomical',solarEvent(a,-18)==null?'--:--':bjt(bjtUtc(solarEvent(a,-18)))); set('stageNautical',solarEvent(a,-12)==null?'--:--':bjt(bjtUtc(solarEvent(a,-12)))); set('stageCivil',solarEvent(a,-6)==null?'--:--':bjt(bjtUtc(solarEvent(a,-6)))); set('stageSunrise',ea==null?'--:--':bjt(bjtUtc(ea)));
    const season=seasonDates[state.season]; const seasonLabel=document.querySelector('.season-line span:first-child'); const dateLabel=document.querySelector('.season-line span:last-child'); if(seasonLabel)seasonLabel.textContent=season[0]; if(dateLabel)dateLabel.textContent=state.date.replaceAll('-','.');
  }
  function setMode(mode) { state.mode=mode;app.dataset.mode=mode;const open=mode!=='dawn-progress';analysis.setAttribute('aria-hidden',String(!open));compare.hidden=mode!=='location-compare';astronomy.hidden=mode!=='astronomy-stage';$('#panelTitle').textContent=mode==='astronomy-stage'?'天文阶段':'地点对比';$('#panelIcon').textContent=mode==='astronomy-stage'?'◌':'⌘';document.querySelectorAll('.mode-switcher [data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode)); }
  function renderRelief() { const parent=terrain.parentElement.getBoundingClientRect(), ir=mapImage.getBoundingClientRect();if(!ir.width)return;const dpr=Math.min(devicePixelRatio||1,1.25);terrain.style.left=`${ir.left-parent.left}px`;terrain.style.top=`${ir.top-parent.top}px`;terrain.style.width=`${ir.width}px`;terrain.style.height=`${ir.height}px`;terrain.width=Math.round(ir.width*dpr);terrain.height=Math.round(ir.height*dpr);const c=terrain.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,ir.width,ir.height);const g=c.createRadialGradient(ir.width*.25,ir.height*.5,0,ir.width*.25,ir.height*.5,Math.max(ir.width,ir.height)*.6);g.addColorStop(0,'rgba(30,91,137,.22)');g.addColorStop(1,'rgba(2,15,31,0)');c.fillStyle=g;c.fillRect(0,0,ir.width,ir.height); }
  function render() { syncMarkers();renderRelief();const ir=mapImage.getBoundingClientRect();if(ir.width)renderSolarField(solar,ir,bjtUtc(state.minute));updatePanel();syncDerivedUi();const clock=$('.clock-line');if(clock)clock.innerHTML=`${bjt(bjtUtc(state.minute))} <small>BJT</small>`;const current=$('#timelineCurrent');if(current)current.textContent=bjt(bjtUtc(state.minute)); }
  function setup() { document.querySelectorAll('.mode-switcher [data-mode]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.mode==='location-compare'&&state.selected.length<2)state.selected=['北京','乌鲁木齐'];setMode(b.dataset.mode);updatePanel();syncDerivedUi();}));document.querySelectorAll('.season-cards [data-season]').forEach((button)=>{button.addEventListener('click',()=>{const season=seasonDates[button.dataset.season];if(!season)return;state.season=button.dataset.season;state.date=season[1];state.minute=300;document.querySelectorAll('.season-cards button').forEach((item)=>item.classList.toggle('active',item===button));const range=$('#timeRange');if(range)range.value=String(state.minute);render();});});$('#closePanel').addEventListener('click',()=>setMode('dawn-progress')); const shortcuts=['北京','乌鲁木齐','广州','哈尔滨','拉萨','海口'];const layer=$('#cityShortcuts');shortcuts.forEach(name=>{const b=document.createElement('button');b.type='button';b.dataset.city=name;b.textContent=name;if(!state.points.some(p=>p.name===name)){b.disabled=true;b.title='暂无经人工核验的 V 坐标';}layer.append(b);});layer.addEventListener('click',e=>{const b=e.target.closest('[data-city]');if(b&&!b.disabled)selectCity(b.dataset.city);}); let range=$('#timeRange');if(!range){range=document.createElement('input');range.id='timeRange';range.type='range';range.min=180;range.max=600;range.value=state.minute;range.className='time-range';$('.timeline-track-wrap').prepend(range);}range.addEventListener('input',()=>{state.minute=Number(range.value);render();});$('#playToggle').addEventListener('click',()=>{state.playing=!state.playing;$('#playToggle').textContent=state.playing?'Ⅱ':'▶';$('#playToggle').setAttribute('aria-pressed',String(state.playing));if(state.timer)clearInterval(state.timer);if(state.playing)state.timer=setInterval(()=>{state.minute=state.minute>=600?180:state.minute+1;range.value=state.minute;render();},180);}); }
  async function load() { try { const r=await fetch('assets/map/metadata/control-points.json',{cache:'no-store'}); const raw=(await r.json()).controlPoints||[]; return raw.map(adapt).filter(Boolean); } catch(e) { console.warn('Control points fetch failed; using audited fallback.',e); return fallback; } }
  load().then(points=>{state.points=points.length?points:fallback;placeMarkers(state.points);setup();state.selected=['北京'];setMode('dawn-progress');render();});mapImage.addEventListener('load',render);window.addEventListener('resize',render,{passive:true});
})();
